name: Test and Linters

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test-and-code-quality:
    name: 🧪 Test and Linters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Get dependencies
        run: |
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.1
          args: --timeout 8m
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Test
        run: |
          export APP_ENV=test
          go test ./... -v -short -coverprofile packageWithpbgo.cov -coverpkg=./...
          grep -vE '^gofr\.dev\/.*\.pb\.go' packageWithpbgo.cov > profile.cov
          go tool cover -func profile.cov
